package link.sharedworld.host;

public enum SharedWorldReleasePhase {
    IDLE,
    BEGINNING_BACKEND_FINALIZATION,
    BACKEND_FINALIZING,
    WAITING_FOR_VANILLA_DISCONNECT,
    DISCONNECTING_LOCAL_WORLD,
    FORCED_DISCONNECTING,
    UPLOADING_FINAL_SNAPSHOT,
    COMPLETING_BACKEND_FINALIZATION,
    COMPLETE,
    ERROR_RECOVERABLE,
    TERMINATED_DELETED,
    TERMINATED_REVOKED
}
